name: Ajouter Commentaire Automatique

on:
   workflow_run:
    workflows: ["Générer Image et Déployer"]
    types:
      - completed

permissions:
  contents: write

jobs:
  comment-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Télécharger l'artefact
        uses: actions/download-artifact@v4
        with:
          name: images-generees
          path: ./artifacts/

      - name: Récupérer le nom de l'image
        run: |
          IMAGE_PATH=$(find ./artifacts -name "*.png" | head -n 1)
          IMAGE_NAME=$(basename "$IMAGE_PATH")

          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

      - name: Construire l'URL de l'image
        run: |
          IMAGE_URL="https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/images/${IMAGE_NAME}"
          echo "IMAGE_URL=$IMAGE_URL" >> $GITHUB_ENV

      - name: Récupérer le message du commit
        run: |
          echo "MESSAGE=${{ github.event.workflow_run.head_commit.message }}" >> $GITHUB_ENV
      
      - name: Ajouter un commentaire sur le commit
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const message = process.env.MESSAGE;
            const imageUrl = process.env.IMAGE_URL;

            const body = `### 🎨 Image générée automatiquement

                        **Message du commit :**
                        ${message}

                        ![Image Générée](${imageUrl})
                        `;

            github.rest.repos.createCommitComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: context.payload.workflow_run.head_sha,
              body: body
            });